### ISSUE TITLE
More custom round options

### ISSUE THREAD

**Issue by crashzk** [Summer-16/CSGO_CustomRounds#1]
More custom round options, exemplos:
- Round AK-47 + HE Grenades;
- Round AWP + Zeus;
- Round Scout + 1HP;

That is, several types of rounds, so we can do some events per round.

**Comment by Summer-16** [comment]
Does it even works I mean the current plugin, because I have never tested it xD

----------------

Edit: New version working (Self-tested)

**Comment by Summer-16** [comment]
all weapons type are added in custom rounds list
